# Build stage
FROM node:18-alpine AS builder
WORKDIR /app

# Accept env vars as build args for React
ARG REACT_APP_API_URL
ARG REACT_APP_BOT_NAME
ARG REACT_APP_BOT_TAGLINE
ARG REACT_APP_ACCENT
ARG REACT_APP_ORG_NAME
ARG REACT_APP_LOGO_URL
ARG REACT_APP_THEME_COLOR
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_BOT_NAME=$REACT_APP_BOT_NAME
ENV REACT_APP_BOT_TAGLINE=$REACT_APP_BOT_TAGLINE
ENV REACT_APP_ACCENT=$REACT_APP_ACCENT
ENV REACT_APP_ORG_NAME=$REACT_APP_ORG_NAME
ENV REACT_APP_LOGO_URL=$REACT_APP_LOGO_URL
ENV REACT_APP_THEME_COLOR=$REACT_APP_THEME_COLOR

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/app.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
